framework:
    messenger:
        default_bus: messenger.bus.default
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            sync: 'null://'
        routing:
            'App\Message\RunPluginManagerMessage': async
