parameters:
    platformsh.project_id: '%env(PLATFORMSH_PROJECT_ID)%'
    platformsh.cli_token: '%env(PLATFORMSH_CLI_TOKEN)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'


    Platformsh\Client\Connection\Connector:
        arguments:
            $config:
                api_url: 'https://api.platform.sh'
                accounts: 'https://api.platform.sh/'
                centralized_permissions_enabled: true

    Platformsh\Client\PlatformClient:
        arguments:
            $connector: '@Platformsh\Client\Connection\Connector'

    App\Service\DemoDeployer\PlatformShDeployer:
        arguments:
            $projectId: '%platformsh.project_id%'
            $projectDir: '%kernel.project_dir%'
        tags:
            - { name: 'app.demo_deployer', alias: 'platformsh' }
