parameters:
    store_deployer.target: '%env(STORE_DEPLOYER_TARGET)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'
            - '../src/StoreDesigner/Dto/'
            - '../src/StoreDesigner/Message/'


    App\StoreDeployer\Controller\:
        resource: '../src/StoreDeployer/Controller'
        tags: ['controller.service_arguments']
    App\StoreDesigner\Controller\:
        resource: '../src/StoreDesigner/Controller'
        tags: ['controller.service_arguments']

    App\StoreDeployer\Deployer\DynamicStoreDeployer:
        arguments:
            $locator: !tagged_locator
                tag: 'store_deployer.deployer'
                index_by: 'index'
            $target:  '%store_deployer.target%'

    App\StoreDeployer\Deployer\StoreDeployerInterface: '@App\StoreDeployer\Deployer\DynamicStoreDeployer'

    App\StoreDeployer\Deployer\LocalhostDeployer:
        tags:
            - { name: 'store_deployer.deployer', index: 'localhost' }

    App\StoreDeployer\Deployer\PlatformShDeployer:
        tags:
            - { name: 'store_deployer.deployer', index: 'platformsh' }
