parameters:
    platformsh.project_id: '%env(PLATFORMSH_PROJECT_ID)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/StoreDesigner/Dto/'

    App\StoreDesigner\Controller\:
        resource: '../src/StoreDesigner/Controller'
        tags: ['controller.service_arguments']
