parameters:
    platform.project_id: '%env(PLATFORM_PROJECT_ID)%'
    platform.sylius_branch: '%env(SYLIUS_BRANCH)%'
    platform.api_token:   '%env(PLATFORMSH_API_TOKEN)%'
    platform.ssh_key_path: '%env(PLATFORMSH_SSH_KEY_PATH)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'


    Platformsh\Client\Connection\Connector:
        arguments:
            $config:
                api_url: 'https://api.platform.sh'
                accounts: 'https://api.platform.sh/'
                centralized_permissions_enabled: true

    Platformsh\Client\PlatformClient:
        arguments:
            $connector: '@Platformsh\Client\Connection\Connector'

    App\Service\DemoDeployer\PlatformShDeployer:
        arguments:
            $projectId:    '%platform.project_id%'
            $syliusBranch: '%platform.sylius_branch%'
            $apiToken:     '%platform.api_token%'
            $sshKeyPath:   '%platform.ssh_key_path%'
        tags:
            - { name: 'app.demo_deployer', alias: 'platformsh' }
