parameters:
    platform.project_id: '%env(PLATFORM_PROJECT_ID)%'
    platform.sylius_branch: '%env(SYLIUS_BRANCH)%'
    platform.cli_token:   '%env(PLATFORMSH_CLI_TOKEN)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'


    Platformsh\Client\Connection\Connector:
        arguments:
            $config:
                api_url: 'https://api.platform.sh'
                accounts: 'https://api.platform.sh/'
                centralized_permissions_enabled: true

    Platformsh\Client\PlatformClient:
        arguments:
            $connector: '@Platformsh\Client\Connection\Connector'

    App\Service\DemoDeployer\PlatformShDeployer:
        arguments:
            $projectId:    '%platform.project_id%'
            $platformCliToken:   '%platform.cli_token%'
            $projectDir: '%kernel.project_dir%'
        tags:
            - { name: 'app.demo_deployer', alias: 'platformsh' }

    App\MessageHandler\RunPluginManagerMessageHandler:
        arguments:
            $syliusWorkingDir: '%env(resolve:SYLIUS_STANDARD_DIR)%'